classDiagram
    class Estudiante {
        -id: int
        -nombre: string
        -email: string
        -carrera: string
        +registrarusuario(): void
        +editarPerfil(): void
        +consultarCursosDisponibles(): List<Curso>
        +consultarCursosMatriculados(): List<Grupo>
    }

    class Profesor {
        -idProfesor: int
        -nombre: string
        -email: string
        -especialidad: string
        +idasignarCurso(): void
        +consultarCursosAsignados(): List<Curso>
    }

    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }

    class Grupo {
        -idGrupo: int
        -idCurso: int
        -idProfesor: int
        -idPeriodo: int
        -capacidad:int 
        -numerogrupo: int
        -horario: string
        +idProfesor(): void
        +idEstudiante(): void
    }

    class Periodo {
        -año: int
        -nombre: string
        -activo: boolean
        +iniciarPeriodo(): void
        +finalizarPeriodo(): void
    }

    class Matricula{
        -idMatricula: int
        -idEstudiante: int
        -idGrupo: int
        -fechaMatricula: date
    }

    Estudiante "1" --> "1..*" Matricula : realiza
    Matricula "1" --> "1" Grupo : pertenece a
    Grupo "1..*" --> "1" Curso : imparte
    Profesor "1" --> "1..*" Grupo : imparte
    Periodo "1..*" --> "1..*" Grupo : se ofrece en